# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: yizhang <yizhang@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/09/26 10:26:19 by yizhang       #+#    #+#                  #
#    Updated: 2023/09/26 10:29:02 by yizhang       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = 
CC = g++
FLAGS = -Wall -Werror -Wextra
SRC = 

all: $(NAME)

$(NAME):
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

.PHONY: all clean