# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: yizhang <yizhang@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/11/07 17:27:06 by yizhang       #+#    #+#                  #
#    Updated: 2023/11/07 17:29:54 by yizhang       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = zombieHorde
FLAG = -Wall -Wextra -Werror
CC = c++